### PR TITLE
Multi-touch (drop-in replacement, backward compatible), BtnA - BtnC as well as user-defined Arduino style buttons in any touch rectangle

### PR DESCRIPTION
**Pull request by ropg**
```
M5Stack Core2 touch library

	Touch is provided by a FocalTech FT6336 chip, which supports two
	simultaneous touches (see below for limitation).

	This library is initialised in M5Core2.h. An instance "M5.Touch" exists
	and can be used after you call "M5.begin()".


Two-touch API

	M5.update()
		In the loop() part of your sketch, call "M5.update()". This is the
		only part that talks to the touch interface.

	TouchPoint_t
		Variable type to hold a touchpoint. Has members x and y that hold
		the coordinates of a touch.

	uint8_t M5.Touch.points
		Contains the number of touches detected: 0, 1 or 2.

	TouchPoint_t M5.Touch.point[0], M5.Touch.point[1]
		M5.Touch.point[0] and M5.Touch.point[1] hold the detected touches.
		
	bool M5.Touch.inBox(x0, y0, x1, y1)
		true if any valid touch is found in the supplied rectangle. Can be
		used directly, but you'll be happier with the TouchButton library.

	bool M5.Touch.hasChanged()
		true if anything has moved on the touch screen since the last time
		this function was called.


Note about multi-touch

	The M5Stack Core2 touch display is only multi-touch in one dimension.
	What that means is that it can detect two separate touches only if they
	occur on different vertical positions. This has to do with the way the
	touch screen is wired, it's not something that can be changed in
	software. So you will only ever see two points if they do not occur
	side-by-side. Touches that do happen side-by-side blend into one touch
	that is detected somewhere between the actual touches.

	While this limits multi-touch somewhat, you can still create multiple
	buttons and see two that are not on the same row simultaneously.


Legacy single touch API

	TouchPoint_t
		Variable type to hold a touchpoint. Has members x and y that hold
		the coordinates of a touch.

	bool M5.Touch.ispressed()
		true when the touch screen is pressed.

	TouchPoint_t M5.Touch.getPressedPoint()
		Returns the point that is being pressed, or (-1,-1) is nothing is
		pressed. In case two points are pressed, this will return one of
		them.

	HotZone_t
		Defines a zone on the screen, comes with built-in functions to test
		if a given point is within that zone. Similar but more enhanced
		functionality is provided by the TouchButton library, see below.


TouchButton library

	The TouchButton library is initialised together with the touch library,
	and offers a higher level way to interact with the touch screen. Using
	this library you can create virtual buttons for any given rectangle of
	the screen. These buttons then have the same API as the standard
	Arduino buttons, except you can define optional handler functions that
	get called whenever the button is pressed or released.

	The library is called M5TouchButton and the documentation is in the
	header file that lives at src/utility/M5TouchButton.h in this library.


Example

	The examples/Basics directory has an example sketch called "touch" that
	shows both the touch library and the TouchButton library in action.
	Should be pretty self-explanatory.
```

&nbsp;

```
M5Stack Core2 M5TouchButton library version 1.0

	Implements Arduino button library compatible buttons for any chosen
	rectangle on the M5Stack Core2 touch screen. Up to two buttons can be
	pressed simultaneously.


Basic usage

	For this to work, M5.update() has to be ran to scan for button presses,
	so make sure to put that in the loop() part of your sketch.

	To create a button, just create a button variable that defines the area
	on the touch screen for the button. E.g.:

		TouchButton testButton(0, 0, 50, 50);

	The format is x0, y0, x1, y1 where x0, y0 is the left top of the button
	and x1, y1 is the right bottom. From here on you can use all the
	standard Arduino button functions such that testButtton.isPressed()
	will now tell you if the top left of the screen is touched.

	Buttons will be deleted from the list if their variables go out of
	focus, so if you define buttons in a subroutine, they will not be in
	your way anywhere else.

	If button areas overlap, both buttons will become pressed if the
	overlap is touched. Note that you cannot ever press two non-overlapping
	buttons simultaneously because the M5Core2 touch screen is not
	multi-touch.

	The three buttons BtnA, BtnB and BtnC from the older M5Stack units come
	already implemented as buttons that lie just below the screen where the
	three circles are. If you want them to be a little bigger and also
	cover the area of the screen where you may be showing labels for the
	buttons, simply raise the top of the buttons like this:

		 M5.BtnA.y0 = M5.BtnB.y0 = M5.BtnC.y0 = 220;

	The screen is 320 x 240 pixels, the touch sensor is 320 x 280, 40
	pixels are below the screen.
	

Note about multi-touch

	The M5Stack Core2 touch display is only multi-touch in one dimension.
	What that means is that it can detect two separate touches only if they
	occur on different vertical positions. This has to do with the way the
	touch screen is wired, it's not something that can be changed in
	software. So you will only ever see two points if they do not occur
	side-by-side. Touches that do happen side-by-side blend into one touch
	that is detected somewhere between the actual touches.

	While this limits multi-touch somewhat, you can still create multiple
	buttons and see two that are not on the same row simultaneously.
	

Calling functions automatically

	In addition to the coordinates, you can optionally specify a
	function to be called when a button is pressed, a function for when
	it's released, as well as an id number to figure out what button was
	pressed if multiple buttons are handled by the same function.
	
	Naturally you can also have a separate function for each key in which
	case you doon't need to supply an id number (it defaults to 0).
	Function pointers and id can also be retrieved or set later, with
	btn.fnPress, btn.fnRelease and fn.id. So to attach a function to the
	leftmost button under the screen, simply say:
	
		M5.BtnA.fnPress = myFunction;
		
		
Example

	The examples/Basics directory has an example sketch called "touch" that
	shows both the touch library and the TouchButton library in action.
	Should be pretty self-explanatory.		
```

&nbsp;

```c++
#include <M5Core2.h>

void setup() {
  M5.begin();
}

void loop() {
  M5.update();
  if (M5.Touch.hasChanged()) {
    if (!M5.Touch.points) Serial.print("--");
    if (M5.Touch.points) Serial.printf("x: %d, y: %d        ",  M5.Touch.point[0].x, M5.Touch.point[0].y);
    if (M5.Touch.points == 2) Serial.printf("x: %d, y: %d",  M5.Touch.point[1].x, M5.Touch.point[1].y);
    Serial.println();
  }
}

void btnHandler(TouchButton &btn) {
  M5.Lcd.fillRect(btn.x0, btn.y0, btn.x1 - btn.x0, btn.y1 - btn.y0, btn.isPressed() ? WHITE : BLACK);
}

TouchButton lt = TouchButton(0, 0, 159, 119, btnHandler, btnHandler);
TouchButton lb = TouchButton(0, 120, 159, 240, btnHandler, btnHandler);
TouchButton rt = TouchButton(160, 0, 320, 119, btnHandler, btnHandler);
TouchButton rb = TouchButton(160, 120, 320, 240, btnHandler, btnHandler);
```

### CODE REVIEW

**Comment by felmue** [comment]
Hello @ropg 

thank you very much for taking the time to put this library together. I've ran a quick test and it works as advertised.

Any plans to make it capable of detecting multiple buttons at the same time? I understand the touch IC is capable of detecting more than one touch point concurrently. Right now touching area A and C results in B.

There is a typo in the descriptions (here, .c. and .h file) about how to make buttons A, B and C a little bigger (Very neat feature, btw).

For it to work `y0` and not `y1` needs to be modified, eg. `M5.BtnA.y0 = M5.BtnB.y0 = M5.BtnC.y0 = 220;`

Thanks
Felix

BTW: extending buttons A, B and C fixes the issue I am seeing on my Core2, where the area below the screen doesn't react to touch when the Core2 is not sitting on a metal surface (or held with the other hand). The area below the screen still doesn't work, but the extended area on the screen does. Strange isn't it? Have you noticed that too?

https://community.m5stack.com/topic/2300/capacitive-buttons-only-work-when-holding-core2-or-when-sitting-on-metal-surface

**Comment by ropg** [comment]
Hi,

I fixed the iinstructions y1 -> y0, thanks...

I am using mine sitting on a wooden (well, MDF) table and it works fine without touching it with the other hand. Have not have trouble with the touch.

As for multi-touch: I have not read the datasheet for that chip, but IIRC multi-touch is generally an expensive feature not found in cheaper touch screens. But maybe I will be surprised, will give that a read soon.

**Comment by tobozo** [comment]
FT6336U panel is described as multi-touch on this [product page](https://www.panelook.com/CHX215GG001-V1-0-2-8Inch-FT6336U-One-pointGesture-GG-detail_78499.html) but described as "Touch multi-point" or even "Point Multi-Touch" on other pages, this is confusing

**Comment by ropg** [comment]
Looks to me (after quick first pass from [here](https://www.buydisplay.com/download/ic/FT6236-FT6336-FT6436L-FT6436_Datasheet.pdf) ) that the chip has either two touch points or it will itself decode gestures. The gestures are rather spartan: Move (up, down, left, right) and Zoom (In/Out). Only for the latter gestures would it use multi-touch, so I think putting it it two-point mode is much more interesting. We can always create our own gesture recognition later.

If this all indeed works, I think I'll change M5TouchButton to integrate instead of supplement the functionality now provided by the touch library from M5Stack, providing their API for compatibility. It would be really cool to hear from M5Stack that this is something they'd want to use, because it would suck to all this work for nothing...

**Comment by tobozo** [comment]
Funny enough this also creates the implementation need the other way around: if there is a Button=>Touch emulation on M5Core2, why not a Touch=>Button emulation on M5Core classic ? :thinking:

**Comment by ropg** [comment]
Funny thing is the touch driver seems to read the first touch point only and simply ignore the second. But then why do we then get the middle between two touch points? The chip also returns pressure and size for each touch, I'll try writing something that reads all the relevant registers today.

**Comment by felmue** [comment]
Hi @ropg
I am looking forward to hearing about you findings. I’ve tried to change some parameters myself, like threshold, but I did not notice any difference.
Thanks
Felix

**Comment by felmue** [comment]
Hi @ropg
I am looking forward to hearing about you findings. I’ve tried to change some parameters myself, like threshold, but I did not notice any difference.
Thanks
Felix

**Comment by felmue** [comment]
Hi @ropg
I am looking forward to hearing about you findings. I’ve tried to change some parameters myself, like threshold, but I did not notice any difference.
Thanks
Felix

**Comment by felmue** [comment]
Hi @ropg
I am looking forward to hearing about you findings. I’ve tried to change some parameters myself, like threshold, but I did not notice any difference.
Thanks
Felix

**Comment by ropg** [comment]
I think the chip is set for single touch in the same flash that holds the absolute size of the touch display (320x280) and various other parameters. I assume M5Stack has set these values. I did find a russian page with Arduino code to flash the firmware, but nothing to tell me how to set the basic parameters. Either way, this is where it gets a bit tricky and one might brick one's M5Core.

**Comment by felmue** [comment]
Hi @ropg 
hmm, I did some tests where I've read TD_STATUS (reg 0x02) and it sometimes returns 2 when using two fingers, but it was not very consistent. What I could not get to work is the gestures - GEST_ID (reg 0x01) always returned 0 for me.
Cheers
Felix

**Comment by ropg** [comment]
[This](https://forum.arduino.cc/index.php?topic=651583.0) seems to claim that [this](https://github.com/strange-v/FT6X36/tree/develop) works.

Also lots of people online say that with the standard firmware the gestures do not work.

**Comment by tobozo** [comment]
T.I.L. some panels can claim they have multitouch support by only implementing one of the two axis. 

While this may appear as a partial implementation, it's good to keep that in mind while experimenting (e.g. multi touch only works vertically or horizontally)

**Comment by ropg** [comment]
@tobozo Ha, looking at the behaviour of the output in the M5Stack Factory Test App, that MAY (unconfirmed!) be what's going on here: touches on the same horizontal line blur into one, where touches on a vertical line give you one or the other. 

Meh, that would be kinda lame if true...

**Comment by ropg** [comment]
I need to sign off for the day. Feel free to test the Arduino library from above, that has me most curious now.

**Comment by felmue** [comment]
Hi guys
I've played a bit with the above mentioned library and yes, I can see the `lift up` event which the owner of the library mentioned to be fixed. However playing with `threshold` or `active touchrate` value I don't get a noticeable different behaviour. I am either missing something here or even though parameter settings can be changed in the touch IC I don't think they are actually taken into account.
Felix

**Comment by ropg** [comment]
Check [THIS](https://github.com/ropg/M5Core2/tree/multitouch) out !!

I'll fix the comments tomorrow. Use the sketch in the examples dir to see it work.

**Comment by ropg** [comment]
There, one multi-touch library with everything.... Enjoy

**Comment by felmue** [comment]
Hi @ropg 

nicely done! (And a good test for what's possible with multi-touch and what not, eg. vertical yes, horizontal no.)

Cheers
Felix

**Comment by felmue** [comment]
Hi @ropg 

One small thing. In `M5Core2::begin` you've commented out `Touch.begin()`. Was there a particular reason for that? I found that making the touch IC using `polling mode` instead of `trigger mode` seems to be crucial. With `trigger mode` I get wild flickering on the screen when I touch it. (And `trigger mode` seems to be the default according to the data sheet, so setting `polling mode` explicitly would make sense I think.)

Thanks
Felix

**Comment by ropg** [comment]
No reason, just forgot ro re-ennable.. Fixed...

Shall we abandon this chat and continue as regular issues over on https://github.com/ropg/M5Core2 ?

**Comment by felmue** [comment]
Hi @ropg 

Yes, I guess that would make sense.

Cheers
Felix

**Comment by ropg** [comment]
Closed this. Plan to refile with newer and better tested version that includes gestures and events.

**Pull request closed without merging**
