### PR TITLE
Add speak_sd example for issue #149

### PR DESCRIPTION
**Pull request by GOB52**
Added example for Issue #149.
It reads a wav file from an SD card and plays it back.

### CODE REVIEW

**Comment by Tinyu-Zhao** [comment]
You can put the file speak_sd.wav into the example so that users can use the example faster. Otherwise, you may need to find a suitable wav file, which will take some time.

**Comment by GOB52** [comment]
>I think you can put the file speak_sd.wav into the example folded so that users can use the example faster. Otherwise, you may need to find a suitable wav file, which will take some time.

Does M5 have sound data without rights issues?
If you have it, I will process it, but if not, I will look for CC0 etc.

**Comment by Tinyu-Zhao** [comment]
> > I think you can put the file speak_sd.wav into the example folded so that users can use the example faster. Otherwise, you may need to find a suitable wav file, which will take some time.
> 
> Does M5 have sound data without rights issues? If you have it, I will process it, but if not, I will look for CC0 etc.

I think I can’t find audio files without copyright issues at the moment. 😂

**Comment by GOB52** [comment]
>I think I can’t find audio files without copyright issues at the moment. 😂

OK, I will  find a file with no rights issues.

**Comment by GOB52** [comment]
Resource data, I think it would be better to create a Github Wiki page and upload it there than to put it in a repository.
How about it?

**Comment by Tinyu-Zhao** [comment]
> Resource data, I think it would be better to create a Github Wiki page and upload it there than to put it in a repository. How about it?

I think it's okay, it doesn't have to be placed in the main warehouse, maybe other programs will reuse it.

**Comment by GOB52** [comment]
Created and uploaded wav to GitHub wiki.
Fixes example source code.

**Comment by Tinyu-Zhao** [comment]
I think this is perfect, thanks for the PR.

**Comment by Cupcc** [comment]
why the display filled with purple color after I uploaded this file?

**Pull request merged**
