### PR TITLE
Wrong character usage

### PR DESCRIPTION
**Pull request by PierreRambaud**
CWE-0:The code contains unhandled character(s) (character code=226). Neither unicode nor extended ascii is supported.

### CODE REVIEW

**Comment by PierreRambaud** [comment]
ping @Tinyu-Zhao or @Gitshaoxiang

I also backport the drawing board micropython script into a C app, if you're interested https://github.com/PierreRambaud/drawing-board

**Comment by PierreRambaud** [comment]
Little reminder ping @Tinyu-Zhao or @Gitshaoxiang

**Comment by Tinyu-Zhao** [comment]
Thank you for your help

**Comment by PierreRambaud** [comment]
Thank you @Tinyu-Zhao

**Pull request merged**
