### PR TITLE
Fix for compilation error (see #52) + github workflow on basic examples

### PR DESCRIPTION
**Pull request by tobozo**
This fixes the compilation error `'vector' in namespace 'std' does not have a template type`

### CODE REVIEW

**Comment by tobozo** [comment]
poke @ropg @Tinyu-Zhao 

It would be a good idea to add a github action to install the library and compile a couple of examples, and wait for the test results before publishing a new release.

Let me know if you need help on that.

**Comment by Tinyu-Zhao** [comment]
Thank you for your suggestion, we will link the entry operation of Arduino on the official website to github in the future

**Comment by Tinyu-Zhao** [comment]
> poke @ropg @Tinyu-Zhao 
> 
> 
> 
> It would be a good idea to add a github action to install the library and compile a couple of examples, and wait for the test results before publishing a new release.
> 
> 
> 
> Let me know if you need help on that.

Thank you for your suggestion, we will link the entry operation of Arduino on the official website to github in the future

**Comment by tobozo** [comment]
whoops apologies for spamming I should've used a separate branch

Adding the LibraryBuild.yml fill will add some compilation tests to github actions and trigger the workflow on push or pull request.

All sketches inside the "Basics" example folder will be compiled by a github action, so if you choose to use it, don't forget to check the results of the github action before producing a new release :smile_cat: 

image

**Comment by Tinyu-Zhao** [comment]
> whoops apologies for spamming I should've used a separate branch
> 
> 
> 
> Adding the LibraryBuild.yml fill will add some compilation tests to github actions and trigger the workflow on push or pull request.
> 
> 
> 
> All sketches inside the "Basics" example folder will be compiled by a github action, so if you choose to use it, don't forget to check the results of the github action before producing a new release :smile_cat: 
> 
> 
> 
> image
> 
> 

Thank you for your help! I will try it!

**Comment by tobozo** [comment]
> Thank you for your help! I want to try it!

you can try it by merging this pull request **on a separate branch** (not the master), then visit the `actions` tab

**Pull request merged**
