### PR TITLE
AXP192: fix register in SetLDOVoltage() function.

### PR DESCRIPTION
**Pull request by felmue**

### CODE REVIEW

**Comment by felmue** [comment]
This fixes issue: https://github.com/m5stack/M5Core2/issues/4

**Comment by jesse-schein** [comment]
validated it works well here. The vibration motor is much better when its set at 3.3v

**Review by Hades2001 — COMMENTED** [review]
fix Axp192 SetLDOVoltage() function bug

**Comment by felmue** [comment]
@Hades2001 - any reason you closed this pull-request without merging? Just curious. Thanks.

**Comment by Hades2001** [comment]
Thank you very much for your&nbsp;pull-request,I've recently been trying to fix bugs in Core2 and add some features,This problem has been fixed in the new version，The new version will be submitted in the near future.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "felmue"<notifications@github.com&gt;; 
发送时间: 2020年9月21日(星期一) 下午4:57
收件人: "m5stack/M5Core2"<M5Core2@noreply.github.com&gt;; 
抄送: "有鹿的地方"<1521377294@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [m5stack/M5Core2] AXP192: fix register in SetLDOVoltage() function. (#5)





 
@Hades2001 - any reason you closed this pull-request without merging? Just curious. Thanks.

**Comment by felmue** [comment]
Hello @Hades2001 

ok, thank you for confirming and for working on improving Core2. I appreciate it and I am looking forward to checking out the new features.

Cheers
Felix

**Pull request closed without merging**
